//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.29 at 05:09:52 \uc624\ud6c4 KST 
//


package net.ion.open.oadr2.model.v20b;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="oadrService" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrServiceName"/>
 *                   &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrInfo" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "oadrServices"
})
@XmlRootElement(name = "oadrServiceSpecificInfo")
public class OadrServiceSpecificInfo implements Serializable, Equals, HashCode, ToString
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "oadrService")
    protected List<OadrService> oadrServices;

    /**
     * Default no-arg constructor
     * 
     */
    public OadrServiceSpecificInfo() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public OadrServiceSpecificInfo(final List<OadrService> oadrServices) {
        this.oadrServices = oadrServices;
    }

    /**
     * Gets the value of the oadrServices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the oadrServices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOadrServices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OadrService }
     * 
     * 
     */
    public List<OadrService> getOadrServices() {
        if (oadrServices == null) {
            oadrServices = new ArrayList<OadrService>();
        }
        return this.oadrServices;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            List<OadrService> theOadrServices;
            theOadrServices = (((this.oadrServices!= null)&&(!this.oadrServices.isEmpty()))?this.getOadrServices():null);
            strategy.appendField(locator, this, "oadrServices", buffer, theOadrServices);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof OadrServiceSpecificInfo)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final OadrServiceSpecificInfo that = ((OadrServiceSpecificInfo) object);
        {
            List<OadrService> lhsOadrServices;
            lhsOadrServices = (((this.oadrServices!= null)&&(!this.oadrServices.isEmpty()))?this.getOadrServices():null);
            List<OadrService> rhsOadrServices;
            rhsOadrServices = (((that.oadrServices!= null)&&(!that.oadrServices.isEmpty()))?that.getOadrServices():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "oadrServices", lhsOadrServices), LocatorUtils.property(thatLocator, "oadrServices", rhsOadrServices), lhsOadrServices, rhsOadrServices)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            List<OadrService> theOadrServices;
            theOadrServices = (((this.oadrServices!= null)&&(!this.oadrServices.isEmpty()))?this.getOadrServices():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "oadrServices", theOadrServices), currentHashCode, theOadrServices);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public OadrServiceSpecificInfo withOadrServices(OadrService... values) {
        if (values!= null) {
            for (OadrService value: values) {
                getOadrServices().add(value);
            }
        }
        return this;
    }

    public OadrServiceSpecificInfo withOadrServices(Collection<OadrService> values) {
        if (values!= null) {
            getOadrServices().addAll(values);
        }
        return this;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrServiceName"/>
     *         &lt;element ref="{http://openadr.org/oadr-2.0b/2012/07}oadrInfo" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "oadrServiceName",
        "oadrInfos"
    })
    public static class OadrService implements Serializable, Equals, HashCode, ToString
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected OadrServiceNameType oadrServiceName;
        @XmlElement(name = "oadrInfo", required = true)
        protected List<OadrInfo> oadrInfos;

        /**
         * Default no-arg constructor
         * 
         */
        public OadrService() {
            super();
        }

        /**
         * Fully-initialising value constructor
         * 
         */
        public OadrService(final OadrServiceNameType oadrServiceName, final List<OadrInfo> oadrInfos) {
            this.oadrServiceName = oadrServiceName;
            this.oadrInfos = oadrInfos;
        }

        /**
         * Gets the value of the oadrServiceName property.
         * 
         * @return
         *     possible object is
         *     {@link OadrServiceNameType }
         *     
         */
        public OadrServiceNameType getOadrServiceName() {
            return oadrServiceName;
        }

        /**
         * Sets the value of the oadrServiceName property.
         * 
         * @param value
         *     allowed object is
         *     {@link OadrServiceNameType }
         *     
         */
        public void setOadrServiceName(OadrServiceNameType value) {
            this.oadrServiceName = value;
        }

        /**
         * Gets the value of the oadrInfos property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the oadrInfos property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOadrInfos().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OadrInfo }
         * 
         * 
         */
        public List<OadrInfo> getOadrInfos() {
            if (oadrInfos == null) {
                oadrInfos = new ArrayList<OadrInfo>();
            }
            return this.oadrInfos;
        }

        public String toString() {
            final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
            {
                OadrServiceNameType theOadrServiceName;
                theOadrServiceName = this.getOadrServiceName();
                strategy.appendField(locator, this, "oadrServiceName", buffer, theOadrServiceName);
            }
            {
                List<OadrInfo> theOadrInfos;
                theOadrInfos = (((this.oadrInfos!= null)&&(!this.oadrInfos.isEmpty()))?this.getOadrInfos():null);
                strategy.appendField(locator, this, "oadrInfos", buffer, theOadrInfos);
            }
            return buffer;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof OadrService)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final OadrService that = ((OadrService) object);
            {
                OadrServiceNameType lhsOadrServiceName;
                lhsOadrServiceName = this.getOadrServiceName();
                OadrServiceNameType rhsOadrServiceName;
                rhsOadrServiceName = that.getOadrServiceName();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "oadrServiceName", lhsOadrServiceName), LocatorUtils.property(thatLocator, "oadrServiceName", rhsOadrServiceName), lhsOadrServiceName, rhsOadrServiceName)) {
                    return false;
                }
            }
            {
                List<OadrInfo> lhsOadrInfos;
                lhsOadrInfos = (((this.oadrInfos!= null)&&(!this.oadrInfos.isEmpty()))?this.getOadrInfos():null);
                List<OadrInfo> rhsOadrInfos;
                rhsOadrInfos = (((that.oadrInfos!= null)&&(!that.oadrInfos.isEmpty()))?that.getOadrInfos():null);
                if (!strategy.equals(LocatorUtils.property(thisLocator, "oadrInfos", lhsOadrInfos), LocatorUtils.property(thatLocator, "oadrInfos", rhsOadrInfos), lhsOadrInfos, rhsOadrInfos)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = 1;
            {
                OadrServiceNameType theOadrServiceName;
                theOadrServiceName = this.getOadrServiceName();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "oadrServiceName", theOadrServiceName), currentHashCode, theOadrServiceName);
            }
            {
                List<OadrInfo> theOadrInfos;
                theOadrInfos = (((this.oadrInfos!= null)&&(!this.oadrInfos.isEmpty()))?this.getOadrInfos():null);
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "oadrInfos", theOadrInfos), currentHashCode, theOadrInfos);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

        public OadrService withOadrServiceName(OadrServiceNameType value) {
            setOadrServiceName(value);
            return this;
        }

        public OadrService withOadrInfos(OadrInfo... values) {
            if (values!= null) {
                for (OadrInfo value: values) {
                    getOadrInfos().add(value);
                }
            }
            return this;
        }

        public OadrService withOadrInfos(Collection<OadrInfo> values) {
            if (values!= null) {
                getOadrInfos().addAll(values);
            }
            return this;
        }

    }

}
