//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.29 at 05:09:52 \uc624\ud6c4 KST 
//


package net.ion.open.oadr2.model.v20b;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for oadrCancelReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="oadrCancelReportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110/payloads}requestID"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}reportRequestID" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110/payloads}reportToFollow"/>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/energyinterop/201110}venID" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://docs.oasis-open.org/ns/energyinterop/201110}schemaVersion"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "oadrCancelReportType", propOrder = {
    "requestID",
    "reportRequestIDs",
    "reportToFollow",
    "venID"
})
@XmlRootElement(name = "oadrCancelReport")
public class OadrCancelReport implements Serializable, Equals, HashCode, ToString
{

    private final static long serialVersionUID = 1L;
    @XmlElement(namespace = "http://docs.oasis-open.org/ns/energyinterop/201110/payloads", required = true)
    protected String requestID;
    @XmlElement(name = "reportRequestID", namespace = "http://docs.oasis-open.org/ns/energyinterop/201110", required = true)
    protected List<String> reportRequestIDs;
    @XmlElement(namespace = "http://docs.oasis-open.org/ns/energyinterop/201110/payloads")
    protected boolean reportToFollow;
    @XmlElement(namespace = "http://docs.oasis-open.org/ns/energyinterop/201110")
    protected String venID;
    @XmlAttribute(name = "schemaVersion", namespace = "http://docs.oasis-open.org/ns/energyinterop/201110")
    protected String schemaVersion;

    /**
     * Default no-arg constructor
     * 
     */
    public OadrCancelReport() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public OadrCancelReport(final String requestID, final List<String> reportRequestIDs, final boolean reportToFollow, final String venID, final String schemaVersion) {
        this.requestID = requestID;
        this.reportRequestIDs = reportRequestIDs;
        this.reportToFollow = reportToFollow;
        this.venID = venID;
        this.schemaVersion = schemaVersion;
    }

    /**
     * Gets the value of the requestID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestID() {
        return requestID;
    }

    /**
     * Sets the value of the requestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestID(String value) {
        this.requestID = value;
    }

    /**
     * Gets the value of the reportRequestIDs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportRequestIDs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportRequestIDs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getReportRequestIDs() {
        if (reportRequestIDs == null) {
            reportRequestIDs = new ArrayList<String>();
        }
        return this.reportRequestIDs;
    }

    /**
     * Gets the value of the reportToFollow property.
     * 
     */
    public boolean isReportToFollow() {
        return reportToFollow;
    }

    /**
     * Sets the value of the reportToFollow property.
     * 
     */
    public void setReportToFollow(boolean value) {
        this.reportToFollow = value;
    }

    /**
     * Gets the value of the venID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVenID() {
        return venID;
    }

    /**
     * Sets the value of the venID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVenID(String value) {
        this.venID = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theRequestID;
            theRequestID = this.getRequestID();
            strategy.appendField(locator, this, "requestID", buffer, theRequestID);
        }
        {
            List<String> theReportRequestIDs;
            theReportRequestIDs = (((this.reportRequestIDs!= null)&&(!this.reportRequestIDs.isEmpty()))?this.getReportRequestIDs():null);
            strategy.appendField(locator, this, "reportRequestIDs", buffer, theReportRequestIDs);
        }
        {
            boolean theReportToFollow;
            theReportToFollow = (true?this.isReportToFollow():false);
            strategy.appendField(locator, this, "reportToFollow", buffer, theReportToFollow);
        }
        {
            String theVenID;
            theVenID = this.getVenID();
            strategy.appendField(locator, this, "venID", buffer, theVenID);
        }
        {
            String theSchemaVersion;
            theSchemaVersion = this.getSchemaVersion();
            strategy.appendField(locator, this, "schemaVersion", buffer, theSchemaVersion);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof OadrCancelReport)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final OadrCancelReport that = ((OadrCancelReport) object);
        {
            String lhsRequestID;
            lhsRequestID = this.getRequestID();
            String rhsRequestID;
            rhsRequestID = that.getRequestID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "requestID", lhsRequestID), LocatorUtils.property(thatLocator, "requestID", rhsRequestID), lhsRequestID, rhsRequestID)) {
                return false;
            }
        }
        {
            List<String> lhsReportRequestIDs;
            lhsReportRequestIDs = (((this.reportRequestIDs!= null)&&(!this.reportRequestIDs.isEmpty()))?this.getReportRequestIDs():null);
            List<String> rhsReportRequestIDs;
            rhsReportRequestIDs = (((that.reportRequestIDs!= null)&&(!that.reportRequestIDs.isEmpty()))?that.getReportRequestIDs():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "reportRequestIDs", lhsReportRequestIDs), LocatorUtils.property(thatLocator, "reportRequestIDs", rhsReportRequestIDs), lhsReportRequestIDs, rhsReportRequestIDs)) {
                return false;
            }
        }
        {
            boolean lhsReportToFollow;
            lhsReportToFollow = (true?this.isReportToFollow():false);
            boolean rhsReportToFollow;
            rhsReportToFollow = (true?that.isReportToFollow():false);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "reportToFollow", lhsReportToFollow), LocatorUtils.property(thatLocator, "reportToFollow", rhsReportToFollow), lhsReportToFollow, rhsReportToFollow)) {
                return false;
            }
        }
        {
            String lhsVenID;
            lhsVenID = this.getVenID();
            String rhsVenID;
            rhsVenID = that.getVenID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "venID", lhsVenID), LocatorUtils.property(thatLocator, "venID", rhsVenID), lhsVenID, rhsVenID)) {
                return false;
            }
        }
        {
            String lhsSchemaVersion;
            lhsSchemaVersion = this.getSchemaVersion();
            String rhsSchemaVersion;
            rhsSchemaVersion = that.getSchemaVersion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "schemaVersion", lhsSchemaVersion), LocatorUtils.property(thatLocator, "schemaVersion", rhsSchemaVersion), lhsSchemaVersion, rhsSchemaVersion)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theRequestID;
            theRequestID = this.getRequestID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "requestID", theRequestID), currentHashCode, theRequestID);
        }
        {
            List<String> theReportRequestIDs;
            theReportRequestIDs = (((this.reportRequestIDs!= null)&&(!this.reportRequestIDs.isEmpty()))?this.getReportRequestIDs():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "reportRequestIDs", theReportRequestIDs), currentHashCode, theReportRequestIDs);
        }
        {
            boolean theReportToFollow;
            theReportToFollow = (true?this.isReportToFollow():false);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "reportToFollow", theReportToFollow), currentHashCode, theReportToFollow);
        }
        {
            String theVenID;
            theVenID = this.getVenID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "venID", theVenID), currentHashCode, theVenID);
        }
        {
            String theSchemaVersion;
            theSchemaVersion = this.getSchemaVersion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "schemaVersion", theSchemaVersion), currentHashCode, theSchemaVersion);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public OadrCancelReport withRequestID(String value) {
        setRequestID(value);
        return this;
    }

    public OadrCancelReport withReportRequestIDs(String... values) {
        if (values!= null) {
            for (String value: values) {
                getReportRequestIDs().add(value);
            }
        }
        return this;
    }

    public OadrCancelReport withReportRequestIDs(Collection<String> values) {
        if (values!= null) {
            getReportRequestIDs().addAll(values);
        }
        return this;
    }

    public OadrCancelReport withReportToFollow(boolean value) {
        setReportToFollow(value);
        return this;
    }

    public OadrCancelReport withVenID(String value) {
        setVenID(value);
        return this;
    }

    public OadrCancelReport withSchemaVersion(String value) {
        setSchemaVersion(value);
        return this;
    }

}
