DROP TABLE IDS CASCADE CONSTRAINTS;
CREATE TABLE IDS  (
  TABLE_NAME varchar2(20) NOT NULL,
  NEXT_ID number(30,0)DEFAULT 0 NOT NULL ,
  CONSTRAINT IDS_PK PRIMARY KEY (TABLE_NAME)
);
DROP TABLE SAMPLE CASCADE CONSTRAINTS;
CREATE TABLE SAMPLE (
  ID VARCHAR(16) NOT NULL PRIMARY KEY,
  UPPER_ID VARCHAR(16) DEFAULT '*' NOT NULL,
  NAME VARCHAR(50),
  DESCRIPTION VARCHAR(100),
  USE_YN CHAR(1),
  REG_USER VARCHAR(10)
);
